import {Pipe} from "@angular/core";
import {PricingService} from "../pricing/pricing.service";
import {CurrencyService} from "../services/currency.service";

@Pipe({name: 'autogenerateDiscount', standalone: true, pure: true})
export class DisplayPersistentDiscount {
  constructor(private pricing: PricingService, private currencyService: CurrencyService) {}

  transform(cardPrice: number, name: string): number {
    let discount = this.pricing.generatePersistentDiscount(name);
    return cardPrice * (1 + ( discount || 0) / 100)
  }
}
