export enum GiftcardClassification {
  GAMES = 'GAMES',
  ENTERTAINMENT = 'ENTERTAINMENT',
  STREAMING = 'STREAMING',
  UTILITIES = 'UTILITIES',
  EDUCATION = 'EDUCATION',
  TRAVEL = 'TRAVEL',
  FOOD = 'FOOD',
  OTHER = 'OTHER',
  OPEN_WORLD = 'OPEN_WORLD',
}
