export enum GiftcardClassification {
  POPULARES_HN = 'POPULARES_HN',
  OPEN_WORLD = 'OPEN_WORLD',
  UTILITIES = 'UTILITIES',
  ENTERTAINMENT = 'ENTERTAINMENT',
  FANTASY = 'FANTASY',
  SHOOTER = 'SHOOTER',
  ANIME = 'ANIME',
  OTHER = 'OTHER',
}
